/* Regresión: líneas (unidad, analítica, costo), cotización con retenciones y PDF. */
const {chromium}=require(process.env.PWROOT+'/playwright');
const url='file://'+__dirname+'/erp.html';
const ok=[],bad=[];const chk=(c,m)=>{(c?ok:bad).push(m);};
(async()=>{
  const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
  const p=await b.newPage();
  const errs=[];p.on('pageerror',e=>errs.push(String(e)));
  await p.goto(url);
  await p.waitForSelector('#nav .navbtn');
  await p.click('[data-view="cotizaciones"]');await p.waitForTimeout(200);
  await p.click('[data-action="add"][data-type="cotizacion"]');
  await p.waitForSelector('#lineas .lrow');
  const heads=await p.$$eval('#lineas .lhead span',n=>n.map(x=>x.textContent));
  chk(heads.includes('Unidad')&&heads.includes('Analítica')&&heads.includes('Costo U.'),'encabezados: '+heads.join('|'));
  chk(await p.$('#lineas datalist#fx-uni')!=null&&await p.$('#lineas datalist#fx-ana')!=null,'datalists de unidad y analítica');
  chk(await p.$eval('#lineas .lrow [data-k="unidad"]',e=>e.value)==='PZ','unidad por defecto PZ');
  await p.fill('#f-folio','CPXO-9001');await p.fill('#f-cli','Cliente Prueba');
  const fila=async(i,d,u,a,c,cost,mar)=>{const r=`#lineas .lrow:nth-child(${i}) `;
    await p.fill(r+'[data-k="desc"]',d);await p.fill(r+'[data-k="unidad"]',u);await p.fill(r+'[data-k="analitica"]',a);
    await p.fill(r+'[data-k="cantidad"]',String(c));await p.fill(r+'[data-k="costo"]',String(cost));await p.fill(r+'[data-k="margen"]',String(mar));};
  await fila(1,'Bomba centrifuga','PZ','MANTENIMIENTO',2,1000,20);
  await p.click('#lineas .lineadd');await p.waitForTimeout(80);
  await fila(2,'Servicio instalacion','SERV','OBRA CIVIL',1,500,50);
  await p.click('#lineas .lineadd');await p.waitForTimeout(80);
  await fila(3,'Sobra','PZ','X',1,10,0);
  chk((await p.$$('#lineas .lrow')).length===3,'agregar líneas');
  await p.click('#lineas .lrow:nth-child(3) .l-del');await p.waitForTimeout(80);
  chk((await p.$$('#lineas .lrow')).length===2,'eliminar línea');
  await p.click('#rets .retadd');await p.waitForTimeout(80);
  await p.fill('#rets .rrow:nth-child(1) [data-k="concepto"]','Retención ISR');
  await p.dispatchEvent('#rets .rrow:nth-child(1) [data-k="concepto"]','change');
  await p.waitForTimeout(120);
  const calc=(await p.$eval('#calc',e=>e.textContent)).replace(/\s+/g,' ');
  chk(/Por analítica/.test(calc)&&/MANTENIMIENTO/.test(calc)&&/OBRA CIVIL/.test(calc),'resumen por analítica: '+calc.slice(0,220));
  chk(/\$3,500\.00/.test(calc)&&/Retención ISR/.test(calc),'subtotal y retención en cotización');
  await p.click('#modal form button.primary');await p.waitForTimeout(400);
  const cot=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('fulcrum_erp_v6'));return s.cotizaciones.find(c=>c.folio==='CPXO-9001');});
  chk(cot&&cot.lineas.length===2&&cot.lineas[0].analitica==='MANTENIMIENTO'&&cot.retenciones.length===1,'persistencia: '+JSON.stringify(cot&&{l:cot.lineas.length,a:cot.lineas[0].analitica,r:cot.retenciones}));
  await p.evaluate(id=>document.querySelector(`[data-action="edit"][data-type="cotizacion"][data-id="${id}"]`).click(),cot.id);
  await p.waitForSelector('#lineas .lrow');
  chk(await p.$eval('#lineas .lrow:nth-child(1) [data-k="analitica"]',e=>e.value)==='MANTENIMIENTO','reapertura conserva analítica');
  await p.keyboard.press('Escape');await p.waitForTimeout(150);
  await p.evaluate(id=>document.querySelector(`[data-action="print"][data-type="cot"][data-id="${id}"]`).click(),cot.id);
  await p.waitForTimeout(800);
  const prev=await p.evaluate(()=>{const o=[...document.querySelectorAll('.overlay.on')].pop();return o?o.textContent:'';});
  chk(/PZ/.test(prev)&&/SERV/.test(prev)&&/UNI/.test(prev.toUpperCase()),'el PDF muestra la unidad');
  chk(/RETENCIÓN ISR/i.test(prev),'el PDF muestra la retención');
  chk(errs.length===0,'sin errores JS'+(errs.length?': '+errs.join(' | '):''));
  console.log('OK ('+ok.length+')');ok.forEach(m=>console.log('  ok '+m));
  if(bad.length){console.log('FALLAS ('+bad.length+')');bad.forEach(m=>console.log('  XX '+m));}
  await b.close();process.exit(bad.length?1:0);
})();
